### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by aemrich** [bucktower/skipify#1]
Hey, when I run Skipify Automator tells me that there's a Syntax Error: "Expected end of line, etc. but found identifier."

It points to the "track" in:

``` applescript
on run {input, parameters}

    tell application "Spotify" to next track

    return input
end run
```

Any thoughts why that might be happening? Thanks in advance.

**Comment by bucktower** [comment]
Hey @aemrich, could you tell me which version of OS X you're using? I built and tested this on OS X Yosemite 10.10. Also, do you have the latest version of Spotify?

**Comment by aemrich** [comment]
Hi Buck,

I'm using 10.9.  Would that affect the script?  I've seen people
recommending the same script for use with 10.9 before 10.10 got released,
but it's not working on my computer for some reason.

**Comment by bucktower** [comment]
It shouldn't. What would most likely be the problem, in my mind, is if you have an older version of Spotify that doesn't have the most up-to-date Applescript API, since it seems like it's having trouble when it's giving the actual command to the Spotify application to go to the next song.

**Comment by bucktower** [comment]
However, judging from your error, and that it's thinking of "track" as an identifier, you might want to try:

``` applescript
tell application "Spotify" to next
```

in Automator, or you could try:

``` applescript
tell application "Spotify" to nexttrack
```

As you can see [here](http://books.gigatux.nl/mirror/applescript/0596008503/applescripttmm-chp-14-sect-1.html), that error often means there is an unnecessary space or something extra in that line. The problem is that I can't really test it on my own machine, since my Spotify doesn't recognize those commands.

First, though I'd make sure that Spotify is updated to the most current version. Let me know how it goes!

**Comment by aemrich** [comment]
Ok, I'll try those out, thanks Buck!

I think Spotify is up to date, I just restarted it and it auto-updates (I believe).

**Comment by aemrich** [comment]
When I try next and nexttrack, it tells me that the variable (next/nexttrack) is undefined. Curiouser and curiouser. 

I think the problem might lie in my computer or Automator setup somehow, but, being a noob at these sorts of things, have no idea what it might be.  I guess I'll try restarting and I'll see what happens.

**Comment by bucktower** [comment]
If it says something is undefined, that means that it isn't a valid command. That's what a normal installation of OS X should be getting for next/nexttrack.

**Comment by aemrich** [comment]
Hmm. Ok. Restarted, same issue. No idea what would cause it.

**Comment by bucktower** [comment]
Okay, now you might want to try to see the reference for you installation of Spotify. Try "opening the dictionary" of Applescript commands as described [here](http://apple.stackexchange.com/questions/46521/how-do-i-find-out-the-applescript-commands-available-for-a-particular-app)

**Comment by bucktower** [comment]
^^ Note that that is in the Applescript Editor, not Automator. Here's what mine looks like: 
![screen shot 2015-02-15 at 2 53 24 pm](https://cloud.githubusercontent.com/assets/1170938/6204975/76749e9a-b522-11e4-8998-1fed829243ad.png)

**Comment by aemrich** [comment]
Thanks. I'm looking for my Applescript Editor now, but I don't seem to be able to find it.

**Comment by aemrich** [comment]
Oops, nevermind, got it.

**Comment by aemrich** [comment]
Interesting...it looks like I have two instances of Spotify installed (at least according to the Applescript Dictionary).

**Comment by bucktower** [comment]
Hm. Well, I'd try to look through both and see if you can find the Applescript command for skipping to the next track. After that, I'm not quite sure what you can do, maybe uninstall all Spotify, and then reinstall?

**Comment by aemrich** [comment]
Ok, I found the Apple Script: it's "next track".  Created the script again from scratch, but still the same issue. No idea why.  I also tried uninstalling and reinstalling Spotify. Hmm, no idea why this is happening.

![screenshot 2015-02-15 16 12 44](https://cloud.githubusercontent.com/assets/10985876/6205026/8b7be9c8-b52d-11e4-8615-d09ab1b5083f.png)

**Comment by bucktower** [comment]
Sorry. I'm really not sure from here. This is very weird.

**Comment by aemrich** [comment]
Ok, thanks. I'll try and find some Apple Script forums who might be able to help me out. Thanks for looking at this!

**Comment by bucktower** [comment]
Sure! Let me know if you figure this out!
